// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqSyNetXE0qLoEz9vIraYWwiHjA9Fe-s',
    appId: '1:1023668313737:web:4e8e52c173668dd3783058',
    messagingSenderId: '1023668313737',
    projectId: 'to-do-59ba8',
    authDomain: 'to-do-59ba8.firebaseapp.com',
    storageBucket: 'to-do-59ba8.appspot.com',
    measurementId: 'G-78BMFJD4ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbPeh88P7GeyBPa3nFOBxAraD1eiOPSI',
    appId: '1:1023668313737:android:11b16e76c683559e783058',
    messagingSenderId: '1023668313737',
    projectId: 'to-do-59ba8',
    storageBucket: 'to-do-59ba8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUvvo2P_0E1BV7zjmKE8-otg8rkNw4kEE',
    appId: '1:1023668313737:ios:d248c4e8c7e8406a783058',
    messagingSenderId: '1023668313737',
    projectId: 'to-do-59ba8',
    storageBucket: 'to-do-59ba8.appspot.com',
    iosBundleId: 'com.example.toDo',
  );
}
